/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_facedetect_DetectionBasedTracker */

#ifndef _Included_org_opencv_samples_facedetect_DetectionBasedTracker
#define _Included_org_opencv_samples_facedetect_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeLoadCascadeObj
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeLoadCascadeObj
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeSetMaxObjectSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetMaxObjectSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeSetScaleFactor
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetScaleFactor
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeSetMinNeighbors
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetMinNeighbors
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_opencv_samples_facedetect_DetectionBasedTracker
 * Method:    nativeDetectMultiScale
 * Signature: (JJJDIIII)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDetectMultiScale
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
